### PR TITLE
Check and make sure toolsItem is not a empty stack

### PR DESCRIPTION
**Pull request by Alexandrea**
More detailed information can be found at #5741 By @PurpleIsEverything

### CODE REVIEW

**Comment by PurpleIsEverything** [comment]
Any update on this? It continues to be a huge source of regular crashes for our users very frustrating it's a very simple change.

**Comment by pupnewfster** [comment]
The bigger issue, is that we have stopped development on the 1.12 version of Mekanism and currently our build system is not really setup in a way to easily release an update to it anymore. Though I will leave this open for @aidancbrady to decide how he wants to handle it.

**Comment by PurpleIsEverything** [comment]
Even just a manually pushed release to CurseForge would help quite a bit so pack authors stop using it as the broken release is still in the top recommended slot.

**Comment by aidancbrady** [comment]
Unfortunately we're fully committed to 1.15 development right now, and we really don't have the time or manpower to back port changes. If you make make a home-brew build yourself with the changes, I'd be happy to upload to Curse.

**Comment by PurpleIsEverything** [comment]
We will provide a build with a minor version bump and these fixes shortly.

**Comment by pupnewfster** [comment]
Note: if you are going off of the latest changes on our 1.12 branch please fix the bug introduced by <https://github.com/mekanism/Mekanism/commit/c2144495bdd9467eb0abff52d17c4ec749b6aab3> that breaks the miner's search logic. The fix can be copied from the 1.15 branch: <https://github.com/mekanism/Mekanism/blob/1.15x/src/main/java/mekanism/common/tile/TileEntityDigitalMiner.java#L470-L471> (with the proper renames). Basically it is passing the wrong dimensions, and I never bothered backporting the fix as that commit is not included in a released version.

**Comment by PurpleIsEverything** [comment]
We will make sure that fix is included! Thanks.

**Comment by Alexandrea** [comment]
Just a quick question, got the stuff for our issue ready with minor version bump, but i'm unsure of wat you are asking me looking at the code it should be right its already world? 

cause the only change i can see in  in 1.12 and 1.15 (other then 1.15 uses new region()) is at
`set(i, new Coord4D(x, y, z, dimensionType));` for 1.15 and for 1.12 `set(i, new Coord4D(x, y, z, tileEntity.getWorld().provider.getDimension()));` wich is almost the same prior of c214449 wich was `set(i, new Coord4D(x, y, z, world.provider.getDimension()));` but world was just `World world = tileEntity.getWorld();` 
1.12 does not accept dimensionType only integer for Coord4D

**Comment by pupnewfster** [comment]
https://github.com/mekanism/Mekanism/commit/a34c83f6dbc9d8166b4e1c7daf4ea6c6f8747bc6 is the commit where I fixed it in the 1.15 branch. The issue is it is using radius instead of diameter.

**Comment by Alexandrea** [comment]
ooch got it and saw that wil upload in min

**Comment by Alexandrea** [comment]
Here is the new Mekanism bumped to 391 zip file includes the changes i originally made here for our issue and your issue witch you can see on my repo at e14aafdcc640e3c23524ed986300904c27983bfe and of course using your latest version for 1.12 

File includes all Mekanism things (api/tools/etc) with version bump

[Mekanism-1.12.2-9.8.3.391.zip](https://github.com/mekanism/Mekanism/files/4258661/Mekanism-1.12.2-9.8.3.391.zip)

**Comment by Alexandrea** [comment]
[Mekanism-1.12.2-9.8.3.391.zip](https://github.com/mekanism/Mekanism/files/4258718/Mekanism-1.12.2-9.8.3.391.zip)

Should also have added ecf7da8bc7bb963c8e76a503a68a67b132ad85db , now i can go to bed! and Thanks for doing this much appreciated

**Pull request closed without merging**
