### PR TITLE
Added config option for disabling extended vein mining for the Meka-Tool

### PR DESCRIPTION
**Pull request by halvors**
Added config option for disabling extended vein mining for the Meka-Tool, this also removes HUD and Module Tweaker UI for extended vein mining when disabled.

Think this is the way to best integrate it with the existing code.

### CODE REVIEW

**Comment by halvors** [comment]
This implements feature requested in issue #6436

**Comment by pupnewfster** [comment]
I need to review this PR further but I would sort of rather it just use the same config option as the atomic disassembler does for extended vein mining (and adjust the comment on that config option slightly)

**Comment by halvors** [comment]
@pupnewfster I see, that is a fairly small change, just not sure under what category in config to place it in, there is no general category in gear config, should it be in some other config file?

**Comment by halvors** [comment]
Should i put it directly under the General category in general.toml or should it still be in gear.toml somehow?

**Comment by pupnewfster** [comment]
Hmm actually on second thought how you have the config now is fine, given a pack dev may want to allow the meka tool (which is a later game item) have generic vein mining but not allow the atomic disassembler.

**Comment by halvors** [comment]
I see, good. That was my initial thought.

**Comment by pupnewfster** [comment]
Ended up having to do some cleanup due to the implementation not being ideal in terms of how data was being handled if values changed or things, but I believe it works fine now.

**Pull request merged**
