### PR TITLE
Batter first person looking for flamethrower.

### PR DESCRIPTION
**Pull request by FierceManul**
Batter first person looking for flamethrower.
屏幕截图(184)

### CODE REVIEW

**Review by pupnewfster — CHANGES_REQUESTED** [review]
Firstly there is no reason for all the spacing changes that are happening in this file (please revert that), and secondly this will not be merged unless you or someone else fixes/moves the location the flame particle hovers while it is idle (that thing that in your picture is in the middle, of the screen and is no longer at the tip of the flamethrower)

**Comment by FierceManul** [comment]
But i don't know how to do. The original version is really ugly. sad ╯︿╰

**Comment by thiakil** [comment]
https://github.com/mekanism/Mekanism/blob/1.16.x/docs/GoogleStyle4Indents.xml
That's our code style, you can import it if you're using IDEA.

**Comment by pupnewfster** [comment]
And this is where the math happens: https://github.com/mekanism/Mekanism/blob/1.16.x/src/main/java/mekanism/client/render/RenderTickHandler.java#L247-L265

**Comment by pupnewfster** [comment]
Went ahead and manually merged this in https://github.com/mekanism/Mekanism/commit/e12a95fec6362cbdd111f9d5f815cc58220b4858 and also adjusted the flame's rendering to be in the correct spot, so this improvement will be included in 10.0.18 once it is released.

**Pull request closed without merging**
