### PR TITLE
Fix armor items that shouldn't be enchantable being it anyways

### PR DESCRIPTION
**Pull request by ToMe25**
## Changes proposed in this pull request:
 - Fix some armor items being enchantable that shouldn't be.

### CODE REVIEW

**Comment by pupnewfster** [comment]
I believe all of these could be: `return material.getEnchantability() > 0 && super.isBookEnchantable(stack, book);`

**Comment by ToMe25** [comment]
i noticed just after publishing it could also just be `return material.getEnchantability() > 0;`, i will update that later.

**Comment by ToMe25** [comment]
done.

**Comment by ToMe25** [comment]
btw i suggest adding a Thorns Unit as a replacement for the Thorns enchantment on the MekaSuit.

**Pull request merged**
