### PR TITLE
Qio recipe adjustments

### PR DESCRIPTION
**Pull request by thiakil**
## Changes proposed in this pull request:
image
image
image
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by pupnewfster** [comment]
That's a lot of ender pearls (which often are super annoying to get as a player), though I suppose it makes sense given it has no cables. Slightly unsure if it semi borders on being too early for it not requiring power (though I think that is just something we will have to experiment with, and it seems like it might be far enough back anyway).

This does mean that in some ways a digital miner is more expensive, which is not a bad thing. The one recipe that uses a teleportation core that we may want to change though is for the security desk. as making that require four ender pearls seems like overkill.

**Comment by pupnewfster** [comment]
I adjusted a few of the recipes and fixed the merge conflict

image
image
image
image

**Comment by thiakil** [comment]
Lgtm

**Comment by krzj** [comment]
I have 1.20.1

**Pull request merged**
