### PR TITLE
Fix players with GravitationalModulation MekaSuit falling in spectator mode.

### PR DESCRIPTION
**Pull request by ToMe25**
## Changes proposed in this pull request:
 * Fix players with a MekaSuit Bodyarmor with a GravitationalModulationUnit enabled falling in spectator mode.

### CODE REVIEW

**Comment by pupnewfster** [comment]
I think it is getting to the point it may almost make more sense to add a method to `MekanismUtils` that checks creative or spectator status. (Or not both of them, not sure which way it would make more sense for the method to be declared). Given doing a quick search for `.isCreative()` shows a couple other locations that could probably also use check against the player being in spectator. (Mainly pertaining to the fact that spectators probably should not be affected by radiation).

**Comment by ToMe25** [comment]
yes, that sounds like a good idea, but how should that be named?
isGod or canFly are the most reasonable name i could come up with.

**Comment by pupnewfster** [comment]
Not sure to be honest, could also have the default be inverted and have it be something like `isPlayingGamemode`

**Comment by ToMe25** [comment]
ok will do that.

**Pull request merged**
