### PR TITLE
Implement Fill Held toggle for Electrolytic Breathing Unit

### PR DESCRIPTION
**Pull request by beholderface**
## Changes proposed in this pull request:
This adds a toggle to the electrolytic breathing unit that controls whether it will try to fill held items with gas, as I described in https://github.com/mekanism/Mekanism-Feature-Requests/issues/230. 
That second commit in the pull request is just undoing the auto-formatting that I told Eclipse to do before reading the contribution guidelines.

### CODE REVIEW

**Comment by beholderface** [comment]
The fourth commit is me fixing a major error I made when removing the autoformatting. It has been tested, unlike the second and third commits.

**Comment by pupnewfster** [comment]
1. Please target the `v10.1` branch over the default 1.16.x branch as that is the one that is currently under development. The main reason it is in a separate branch still is in case some gamebreaking bug comes up that we need to fix before 10.1.
2. Lang changes should only be done to `en_us` and `en_ud` other lang entries are done via crowdin as needed/if they are different than english. Lang changes also should be made for en_us via data generators (`MekanismLangProvider` and running runData), as otherwise they will just be deleted the next time the data generator is ran.
3. The spacing for the changes in ModuleMekaSuit seems rather screwed up.

**Comment by beholderface** [comment]
ok I believe I have fixed the issues with the lang files but I don't really know what to do about spacing being screwed up

**Comment by beholderface** [comment]
I've started working on redoing my code based on the v10.1 branch

**Comment by beholderface** [comment]
I've finished redoing my code but I don't see any option to put it in this pull request (something to do with the branch it started with maybe, idk), is there a way to do that or should I close this pull request and make a new one with the redone code?

**Comment by pupnewfster** [comment]
You in theory could force push to your branch, though you may find it simpler to just close and make a new one that started from the 10.1 branch just due to the mass number of changes between the two branches.

**Pull request closed without merging**
