### PR TITLE
API Enhancements

### PR DESCRIPTION
**Pull request by DrParadox7**
## Changes proposed in this pull request:
Adds API for the Chemical Injection Chamber.

Usable gases are no longer hardcoded and can be added with:

`GasifyableItems.registerGasifyables("<OredictionaryEntry>", GasRegistry.getGas("<GasName>"), <quantity>);`

This allows for both Mekanism and other mods to modify the valid gases it can accept as well as items to gasify for their own recipes.

### CODE REVIEW

**Comment by SirEndii** [comment]
Thicc

**Comment by DrParadox7** [comment]
Wrong Fork...😰

**Comment by TureBentzin** [comment]
Legendary

**Comment by SirEndii** [comment]
> Legendary

Indeed

**Pull request closed without merging**
