### PR TITLE
Fix Crash when adding a dot or a E...

### PR DESCRIPTION
**Pull request by ToMe25**
...to the Laser Amplifier Delay.

### CODE REVIEW

**Comment by ToMe25** [comment]
lol. why does it say there are so many contributions? The most of them should not listed there because they also happened here.

**Comment by thiakil** [comment]
you merged the wrong 1.12 branch, looks like what you merged was what is now 1.12_old

And what is said crash & how does this fix it?

**Comment by ToMe25** [comment]
If you add a dot or a E to the Laser Amplifier Delay field and press Enter it Crashes, and this Fixes it by not calling the Delay Field if the Player presses dot or E.

**Comment by ToMe25** [comment]
so i guess after this i will need to create a new Branch to stop that contributions occurring, right?

**Comment by thiakil** [comment]
basically yeah, then cherry pick your relevant commit. Remember that you can force push it to the same name and it will update the pr.

Is it a new fork or an old fork?

**Comment by ToMe25** [comment]
this is the fork from my first pr.

**Comment by ToMe25** [comment]
1. if i try to make a new pull request with the same name using the Web Interface does that work to update the PR?
2. the original name or the edited?

**Comment by ToMe25** [comment]
so it doesn't works i guess.

**Pull request closed without merging**
