### PR TITLE
Make Refined Obsidian usable for Nether Portals

### LINKED ISSUE #5444: [1.12.2] [suggestion] Make Refined Obsidian usable for Nether Portals
**Describe the the feature you'd like**
I would like to be able to make Nether Portals out of Refined Obsidian.

**Additional context**
I would realy like to see this working:

### PR DESCRIPTION
**Pull request by ToMe25**
## Changes proposed in this pull request:
* closes #5444
* Make Refined Obsidian usable for Nether Portals.

### CODE REVIEW

**Comment by pupnewfster** [comment]
There are a good number of formatting changes that make the dif somewhat hard to read. My guess is it has to do with we somewhat recently changed our formatting file (mainly to not force hard wrap as much) so I would recommend reimporting it.

**Comment by ToMe25** [comment]
I know there are some formatting changes in that files but i caused them because if i don't auto format it it contains much more stuff that shouldn't be there in the new parts and i don't know how i can use your formatting settings.
So i know but i don't know how i can change that other than formatting the file by hand.

**Comment by pupnewfster** [comment]
What are you using as your compiler? If you are using IntelliJ you can import the stylesheet from here: https://github.com/mekanism/Mekanism/blob/1.12/docs/GoogleStyle4Indents.xml
At some point I may also get around to creating an export for eclipse so that the style settings can easier be imported into it. Worst case given it is small, I can probably just import it briefly run it and also remove a couple line break changes and it should clean the dif up a good bit.

**Comment by ToMe25** [comment]
I am using Eclipse and also know where to import formatting files but it won't use this one so maybe because its for/from IntelliJ.

**Comment by pupnewfster** [comment]
Ya it is for IntelliJ, for now I think I will just quickly redo the formatting just so the dif is easier to read. And sometime next week, given I am busy this weekend, I will try to create a formatting file for Eclipse as well to make things easier.

**Comment by pupnewfster** [comment]
I haven't tested it all that much yet, but I fixed the spacing dif, and also cleaned up some duplicate code/variable names to make the additions a bit easier to read what is going on.

**Comment by ToMe25** [comment]
how can you push to my repo? do people automaticaly have permissions for froks of repos they have permissions for?

**Comment by ToMe25** [comment]
anyways thanks for reformatting that.

**Comment by pupnewfster** [comment]
If I remember correctly GitHub by default gives access to repository maintainers to edit branches for open Pull Requests. (I believe there is a check box on the side near the notifications button for this PR that allows you to disable it, not sure if disabling it changes the default or just disables it for the specific PR)

**Comment by ToMe25** [comment]
Ah ok that is the usage of that Button. was thinking that would disable editing the PR at all for me and others.

**Pull request merged**
